version: "3.8"

services:

  # Marketplace 1 Instance
  mkt1-blockchain-connector:
    container_name: mkt1-blockchain-connector
    image: in2kizuna/blockchain-connector:v1.0.0-SNAPSHOT
    environment:
      - "DATABASE_URL=r2dbc:postgresql://mkt1-postgres:5432/mktdb"
      - "FLYWAY_URL=jdbc:postgresql://mkt1-postgres:5432/mktdb"
      - "ORGANIZATION_ID=VATES-00869735"
    ports:
      - "8081:8080"
    volumes:
      - ./marketplace1-connectorconfig.yml:/src/main/resources/external-config.yml
    links:
      - mkt1-broker-adapter
      - mkt1-dlt-adapter
      - mkt1-postgres
    networks:
      - local_network

  mkt1-dlt-adapter:
    container_name: mkt1-dlt-adapter
    image: aleniet/dlt-adapter:1.1
    environment:
      - "PRIVATE_KEY=0xe2afef2c880b138d741995ba56936e389b0b5dd2943e21e4363cc70d81c89346"
    ports:
      - "8082:8080"
    networks:
      - local_network

  mkt1-broker-adapter:
    container_name: mkt1-broker-adapter
    image: in2kizuna/broker-adapter:v1.0.0-SNAPSHOT
    ports:
      - "8083:8080"
    volumes:
      - ./marketplace1-brokerconfig.yml:/src/main/resources/external-config.yml
    links:
      - mkt1-context-broker
    networks:
      - local_network

  mkt1-context-broker:
    container_name: mkt1-context-broker
    image: fiware/orion-ld:latest
    restart: always
    command: "-dbhost mkt1-mongo -port 1026"
    ports:
      - "1027:1026"
    links:
      - mkt1-mongo
    networks:
      - local_network

  mkt1-mongo:
    container_name: mkt1-mongo
    image: mongo:4.4
    command: "--nojournal"
    volumes:
      - mkt1_data:/data/db
      - mkt1_db_config:/data/configdb
    networks:
      - local_network

  mkt1-postgres:
    container_name: mkt1-postgres
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mktdb
    hostname: mkt1-postgres
    networks:
      - local_network

    # Marketplace 2 Instance

  mkt2-blockchain-connector:
    container_name: mkt2-blockchain-connector
    image: in2kizuna/blockchain-connector:v1.0.0-SNAPSHOT
    environment:
      - "DATABASE_URL=r2dbc:postgresql://mkt2-postgres:5432/mktdb"
      - "FLYWAY_URL=jdbc:postgresql://mkt2-postgres:5432/mktdb"
      - "ORGANIZATION_ID=VATFR-00900867"
    ports:
      - "8084:8080"
    volumes:
      - ./marketplace2-connectorconfig.yml:/src/main/resources/external-config.yml
    links:
      - mkt2-broker-adapter
      - mkt2-dlt-adapter
      - mkt2-postgres
    networks:
      - local_network

  mkt2-postgres:
    container_name: mkt2-postgres
    image: postgres:11
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mktdb
    hostname: mkt2-postgres
    networks:
      - local_network

  mkt2-dlt-adapter:
    container_name: mkt2-dlt-adapter
    image: aleniet/dlt-adapter:1.1
    environment:
      - "PRIVATE_KEY=0xe2afef2c880b138d741995ba56936e389b0b5dd2943e21e4363cc70d81c89346"
    ports:
      - "8085:8080"
    networks:
      - local_network

  mkt2-broker-adapter:
    container_name: mkt2-broker-adapter
    image: in2kizuna/broker-adapter:v1.0.0-SNAPSHOT
    ports:
      - "8086:8080"
    volumes:
      - ./marketplace2-brokerconfig.yml:/src/main/resources/external-config.yml
    links:
      - mkt2-context-broker
    networks:
      - local_network

  mkt2-context-broker:
    container_name: mkt2-context-broker
    image: fiware/orion-ld:latest
    restart: always
    command: "-dbhost mkt2-mongo -port 1026"
    ports:
      - "1028:1026"
    links:
      - mkt2-mongo
    networks:
      - local_network

  mkt2-mongo:
    container_name: mkt2-mongo
    image: mongo:4.4
    command: "--nojournal"
    volumes:
      - mkt2_data:/data/db
      - mkt2_db_config:/data/configdb
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

volumes:
  mkt1_data:
  mkt1_db_config:
  mkt1_mysql:
  mkt2_data:
  mkt2_db_config:
  mkt2_mysql:
